### ISSUE TITLE
请问一下mac上怎么部署？

### ISSUE THREAD

**Issue by CainLuo** [Lbingyi/HerokuV2ray#14]
试了老半天，能ping的通，但是连接不上

**Comment by Lbingyi** [comment]
做返代了么，截图发下看看

**Comment by Pilgrims369** [comment]
部署完打开open app显示 **无应用程序**（图1）而有时是 **应用程序错误**（图2）
![EPA8H)PDNYPCIQ(Y}J4H6 Y](https://user-images.githubusercontent.com/74700101/143719546-961a0f7c-4345-4b51-a913-7ca3aaeb4bba.png)
![5@0}T{ @IET`45}~6~ Q$QW](https://user-images.githubusercontent.com/74700101/143719555-a83fdc00-894e-4b31-b0d0-a5d80f0fe219.png)
