### ISSUE TITLE
fork后仓库被禁用

### ISSUE THREAD

**Issue by awer0201** [Lbingyi/HerokuV2ray#17]
前几天fork后，今天通知仓库被禁用，请问是什么原因？

This repository has been disabled.
Access to this repository has been disabled by GitHub Staff due to a violation of GitHub's terms of service. Contact Support for more information or to request a review of this decision.

**Comment by uragasit** [comment]
同问，昨天发现通知的

**Comment by SongSJR** [comment]
+1

**Comment by grafce** [comment]
一样，申诉也没有用（已改仓库名称）

**Comment by jambestwick** [comment]
me too

**Comment by 2ndMessiah** [comment]
+1 原仓库竟然没被封 摸不到头脑

**Comment by asen1987** [comment]
+1，不能删除，也不能再fork了，sigh

**Comment by aixiu** [comment]
+1，不能删除，也不能再fork了，sigh

**Comment by vipfan** [comment]
+1，不能删除，也不能再fork了

**Comment by 2ndMessiah** [comment]
> +1，不能删除，也不能再fork了，原仓库还在，原仓库，改名，重新建个仓库吧，这么好的源码，封了真是可惜。

这不是没封么？你依然可以git clone 然后建自己的repo再git push啊

**Comment by uragasit** [comment]
> git clone 然后建自己的repo再git push

太专业了，小白不懂啊

**Comment by aixiu** [comment]
我自己经备好份了，防止丢失！~

**Comment by 4409070** [comment]
> 

我也是小白,一起研究,你先安装一个git软件,地址如下
Git 各平台安装包下载地址为：http://git-scm.com/downloads
然后git clone 本项目地址 教程 https://www.runoob.com/git/git-clone.html
git push 应该也是git软件中的命令

对了 前段时间我部署了这个项目,网站打得开,但是节点连不上,你遇到过这种情况吗?

**Comment by 4409070** [comment]
> > git clone 然后建自己的repo再git push
> 
> 太专业了，小白不懂啊

我也是小白,一起研究,你先安装一个git软件,地址如下
Git 各平台安装包下载地址为：http://git-scm.com/downloads
然后git clone 本项目地址 教程 https://www.runoob.com/git/git-clone.html
git push 应该也是git软件中的命令

对了 前段时间我部署了这个项目,网站打得开,但是节点连不上,你遇到过这种情况吗?

**Comment by uragasit** [comment]
> > > git clone 然后建自己的repo再git push
> > 
> > 
> > 太专业了，小白不懂啊
> 
> 我也是小白,一起研究,你先安装一个git软件,地址如下 Git 各平台安装包下载地址为：http://git-scm.com/downloads 然后git clone 本项目地址 教程 https://www.runoob.com/git/git-clone.html git push 应该也是git软件中的命令
> 
> 对了 前段时间我部署了这个项目,网站打得开,但是节点连不上,你遇到过这种情况吗?

谢谢指教，我这就慢慢学
至于节点连不连的上，有这种情况，时断时续，通常连上几十分钟到个把小时自己又断了，过十来分钟又连上了，可能跟cdn节点的质量有关，最多用来做备用或应急用吧。

**Comment by 4409070** [comment]
> > > > git clone 然后建自己的repo再git push
> > > 
> > > 
> > > 太专业了，小白不懂啊
> > 
> > 
> > 我也是小白,一起研究,你先安装一个git软件,地址如下 Git 各平台安装包下载地址为：http://git-scm.com/downloads 然后git clone 本项目地址 教程 https://www.runoob.com/git/git-clone.html git push 应该也是git软件中的命令
> > 对了 前段时间我部署了这个项目,网站打得开,但是节点连不上,你遇到过这种情况吗?
> 
> 谢谢指教，我这就慢慢学 至于节点连不连的上，有这种情况，时断时续，通常连上几十分钟到个把小时自己又断了，过十来分钟又连上了，可能跟cdn节点的质量有关，最多用来做备用或应急用吧。

客气了,其实好简单,git cloneE是拷贝项目到本地,git push是上传项目到你的github,这个就不是fork了

我部署这个项目不成功,就去部署另一个项目了,就是那个特别感谢中的bclswl0827,一部署就成功了,也不知道这个不成功原因在哪.

不过那个只有一个协议,没有这个协议多.

你说的很对,当个备用还是可以的.

**Comment by Dimitri2020007** [comment]
> > > > > git clone 然后建自己的repo再git push
> > > > 
> > > > 
> > > > 太专业了，小白不懂啊
> > > 
> > > 
> > > 我也是小白,一起研究,你先安装一个git软件,地址如下 Git 各平台安装包下载地址为：http://git-scm.com/downloads 然后git clone 本项目地址 教程 https://www.runoob.com/git/git-clone.html git push 应该也是git软件中的命令
> > > 对了 前段时间我部署了这个项目,网站打得开,但是节点连不上,你遇到过这种情况吗?
> > 
> > 
> > 谢谢指教，我这就慢慢学 至于节点连不连的上，有这种情况，时断时续，通常连上几十分钟到个把小时自己又断了，过十来分钟又连上了，可能跟cdn节点的质量有关，最多用来做备用或应急用吧。
> 
> 客气了,其实好简单,git clone是拷贝项目到本地,git push是上传项目到你的github,这个就不是fork了
> 
> 我部署这个项目不成功,就去部署另一个项目了,就是那个特别感谢中的bclswl0827,一部署就成功了,也不知道这个不成功原因在哪.
> 
> 不过那个只有一个协议,没有这个协议多.
> 
> 你说的很对,当个备用还是可以的.

被ban掉的可能：

1.仓库无licenses
2.有license多以gpl为主
3.好吧你知道的太多了，好自为之吧

**Comment by ssfq** [comment]
> > git clone 然后建自己的repo再git push
> 
> 太专业了，小白不懂啊

我也是小白，所以看这里：
new，然后import
