### ISSUE TITLE
项目已经被heroku屏蔽了

### ISSUE THREAD

**Issue by sdshdv** [Lbingyi/HerokuV2ray#2]
创建的时候会提示：
无法创建项目：
我们无法部署您的应用程序，因为源代码违反了 Salesforce 可接受使用和面向外部的服务政策。

**Comment by Lbingyi** [comment]
Fork 本专案后，将 README.md 中的 Lbingyi 替换为自己的用户名后，再进行部署。

**Comment by jambestwick** [comment]
最近又被github封了，说什么违反开源协议规定好像

**Comment by muxiao0001** [comment]
虽然下午刚更新，但现在好像又被禁了。还是说是我个人的问题？
