### ISSUE TITLE
For shadowsocks, Ican't find the shadowsocks-xray-plugin

### ISSUE THREAD

**Issue by BlueKanbu** [Lbingyi/HerokuV2ray#21]
When I try to use shadowssocks, according to Reademe, I need to download shadowsocks-xray-plugin, but I can't find the relevant resources in github, is there an alternative?

**Comment by 4409070** [comment]
https://github.com/shadowsocks/v2ray-plugin

I don’t know if the project at this address can help you

**Comment by 4409070** [comment]
https://github.com/teddysun/xray-plugin

I don’t know if the project at this address can help you
