### ISSUE TITLE
heroku好像已经封禁了这个玩意了，fork到自己仓库也不行

### ISSUE THREAD

**Issue by xinghenyu** [Lbingyi/HerokuV2ray#25]
显示Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by Lbingyi** [comment]
> 显示Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

已更新
