### ISSUE TITLE
是不是又被封了，元素周期表可以开，带路径就badRequest

### ISSUE THREAD

**Issue by mastomato** [Lbingyi/HerokuV2ray#38]

**Comment by Lbingyi** [comment]
> _未提供说明。_

客户端设置错误

**Comment by mastomato** [comment]
是创建的问题吗？设置路径这里？创建完可以打开应用地址，但是如果加路径会badRequest
，设置客户端以后也连不上

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月14日(周四) 下午2:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lbingyi/HerokuV2ray] 是不是又被封了，元素周期表可以开，带路径就badRequest (Issue #38)




  
未提供说明。
  
客户端设置错误

**Comment by Lbingyi** [comment]
> Reference in new issue

提供下客户端设置截图

**Comment by mastomato** [comment]
重新搭了一遍，可以了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lbingyi/HerokuV2ray] 是不是又被封了，元素周期表可以开，带路径就badRequest (Issue #38)





  
Reference in new issue
  
提供下客户端设置截图
 
&mdash;

**Comment by SaNdSssss** [comment]
昨天，我的也被封了，看了你的回答，我也重新搭了一遍还是不行，求解，老哥

**Comment by SaNdSssss** [comment]
> > Reference in new issue
> 
> 提供下客户端设置截图



> 重新搭了一遍，可以了，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月14日(星期四) 下午3:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Lbingyi/HerokuV2ray] 是不是又被封了，元素周期表可以开，带路径就badRequest (Issue #38) Reference in new issue 提供下客户端设置截图 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;·

**Comment by SaNdSssss** [comment]
你们的客户端是怎么配置的？

**Comment by Lbingyi** [comment]
> 你们的客户端是怎么配置的？

![Snipaste_2022-04-15_21-36-18](https://user-images.githubusercontent.com/5351277/163577277-83d718b3-42cc-452f-a72e-75b55cd056cf.png)
