### ISSUE TITLE
fork部署成功，但是app出错了。

### ISSUE THREAD

**Issue by rtrice** [Lbingyi/HerokuV2ray#4]
fork后修改readme,部署成功后，进入xxx.herokuapp.com页面出现下面错误提示，
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

**Comment by kindusmithkindu** [comment]
> restart all dynos

到底在哪说清楚点，我也是这个错误

**Comment by kindusmithkindu** [comment]
好了已经看见了，那该怎么办？

**Comment by rtrice** [comment]
> 进heroku
> 
> 部署项目底下选restart all dynos查看日志是不是有这个错误
> 
> 2021-08-11T15:22:46.200104+00:00 app[web.1]: Error obtaining home directory, please define environment variable HOME.
> 
> 有的话是caddy的锅

确实如此，大佬能修好部署文件吗？

**Comment by Dimitri2020007** [comment]
修改caddy安装源（可选版本）

dockerfile
```
apk add --no-cache --virtual .build-deps ca-certificates nss-tools curl unzip tar tor
mkdir /tmp/caddy
curl -L -H "Cache-Control: no-cache" -o /tmp/caddy/caddy.tar.gz https://github.com/caddyserver/caddy/releases/download/v2.3.0/caddy_2.3.0_linux_amd64.tar.gz && \
tar -zxvf /tmp/caddy/caddy.tar.gz -C /tmp/caddy && \
install -m 755 /tmp/caddy/caddy /usr/local/bin/caddy && \
caddy version && \
rm -rf /tmp/caddy
```

修改caddy执行路径，后半部分的caddyfile不要动
start.sh
```
/usr/local/bin/caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
```

**Comment by rtrice** [comment]
> 修改caddy安装源（可选版本）
> 
> dockerfile
> 
> ```
> apk add --no-cache --virtual .build-deps ca-certificates nss-tools curl unzip tar tor
> mkdir /tmp/caddy
> curl -L -H "Cache-Control: no-cache" -o /tmp/caddy/caddy.tar.gz https://github.com/caddyserver/caddy/releases/download/v2.3.0/caddy_2.3.0_linux_amd64.tar.gz && \
> tar -zxvf /tmp/caddy/caddy.tar.gz -C /tmp/caddy && \
> install -m 755 /tmp/caddy/caddy /usr/local/bin/caddy && \
> caddy version && \
> rm -rf /tmp/caddy
> ```
> 
> 修改caddy执行路径，后半部分的caddyfile不要动
> start.sh
> 
> ```
> /usr/local/bin/caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
> ```

哎，这个方法也无效，还是希望大佬们能修复好....

**Comment by Dimitri2020007** [comment]
试下这个https://github.com/DanyTPG/heroku-vless.git

**Comment by jth445600** [comment]
不能用，网络不通

**Comment by Dimitri2020007** [comment]
> 不能用，网络不通

app打开肯定是404

反代也能看到404就是通的

**Comment by jth445600** [comment]
我知道这个，油管打不开呀

**Comment by kindusmithkindu** [comment]
想个办法让heroku下载caddy1行不行

**Comment by Dimitri2020007** [comment]
alpine linux退到3.12版本，不要wget/curl下载安装

**Comment by jth445600** [comment]
可用版本。https://github.com/jth445600/v2ray-heroku

**Comment by ssehxing** [comment]
> 不能用，网络不通

亲测这个是可行的

**Comment by hyf0988** [comment]
部署好了，进入xxx.herokuapp.com页面有背景音乐，但是ping不通，不能用

**Comment by ssehxing** [comment]
> 部署好了，进入xxx.herokuapp.com页面有背景音乐，但是ping不通，不能用，求解？

我是直接fork，修改了下名字，然后部署，设置反代，设置V2R客户端就可以了，记得设置客户端的时候选VLESS。
部署用的https://github.com/Dimitri2020007/vless-heroku
设置客户端用的
* 客户端下载：https://github.com/2dust/v2rayN/releases
* 代理协议：vless 或 vmess
* 地址：xxx.herokuapp.com
* 端口：443
* 默认UUID：24b4b1e1-7a89-45f6-858c-242cf53b5bdb
* vmess额外id：0
* 加密：none
* 传输协议：ws
* 伪装类型：none
* 伪装域名：xxx.workers.dev(CF Workers反代地址)
* 路径：/24b4b1e1-7a89-45f6-858c-242cf53b5bdb-vless // 默认vless使用(/自定义UUID码-vless)，vmess使用(/自定义UUID码-vmess)
* 底层传输安全：tls
* 跳过证书验证：false

**Comment by Dimitri2020007** [comment]
给你们用不了caddy的提供一个终极解决方法

和caddy的人聊了下变量问题

他们推荐用dockerhub镜像

https://caddy.community/t/error-obtaining-home-directory-please-define-environment-variable-home-caddy2-cannot-run/13333

有能力修改dockerhub镜像的可以试着改一下
可以自定义caddy v2的插件

缺点是装不了别的软件
