### ISSUE TITLE
有个报错

### ISSUE THREAD

**Issue by znwx007** [Lbingyi/HerokuV2ray#9]
returned a non-zero code: 1  最后出来这个提示的报错

**Comment by Fallen-ending** [comment]
=== Fetching app code
=== Building web (Dockerfile)
Sending build context to Docker daemon  299.5kBStep 1/4 : FROM alpine:latest
latest: Pulling from library/alpine
a0d0a0d46f8b: Pulling fs layer
a0d0a0d46f8b: Verifying Checksum
a0d0a0d46f8b: Download complete
a0d0a0d46f8b: Pull complete
Digest: sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a
Status: Downloaded newer image for alpine:latest
 ---> 14119a10abf4
Step 2/4 : ADD entrypoint.sh /opt/entrypoint.sh
ADD failed: stat /var/lib/docker/tmp/docker-builder079486146/entrypoint.sh: no such file or directory

这是我的报错信息，脚本文件没找到，不知道是不是路径出了问题
